### ISSUE TITLE
[Feature Request]: Option to disable skip button injection

### ISSUE THREAD

**Issue by TheBlueKingLP** [intro-skipper/intro-skipper#354]
I use a reverse proxy to inject the skip button since the Docker version of Jellyfin has the permission issue. This allows me to update the Docker container without needing to edit the html manually again after each update.
However this generate errors in the log on every Jellyfin startup.

I propose an option to completely disable the HTML injection feature so that the HTML injection can be handled externally with for example a reverse proxy like traefik, example:
```
    labels:
      - 'traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-html-inject.plugin.rewrite-body.lastModified=true'
      - 'traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-html-inject.plugin.rewrite-body.monitoring.types[0]=text/html'
      - 'traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-html-inject.plugin.rewrite-body.monitoring.types[1]=application/javascript'
      - 'traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-html-inject.plugin.rewrite-body.monitoring.types[2]=text/css'
      - 'traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-html-inject.plugin.rewrite-body.monitoring.types[3]=text/javascript'
      - 'traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-html-inject.plugin.rewrite-body.rewrites[0].regex=</head>'
      - 'traefik.http.middlewares.${COMPOSE_PROJECT_NAME}-html-inject.plugin.rewrite-body.rewrites[0].replacement=<script src="configurationpage?name=skip-intro-button.js"></script></head>'

      - 'traefik.http.routers.${COMPOSE_PROJECT_NAME}.middlewares=${COMPOSE_PROJECT_NAME}-html-inject'
```

**Comment by AbandonedCart** [comment]
Unchecking the option to use the button in 10.10 will not inject the button until it is enabled. That is why enabling the button requires a restart.

**Comment by AbandonedCart** [comment]
I may backport this to 10.9, but with he button enabled by default instead of disabled. There just didn’t seem to be much purpose with 10.9 not having an alternate button provided by the clients.

**Comment by TheBlueKingLP** [comment]
> Unchecking the option to use the button in 10.10 will not inject the button until it is enabled. That is why enabling the button requires a restart.

I just updated to Jellyfin 10.10.0 and Intro Skipper 1.10.10.1, however I cannot seems to find the option you mentioned, where would that be located at?
![image](https://github.com/user-attachments/assets/80b3ecda-5256-49f5-a999-9c48a58c7f2c)

**Comment by AbandonedCart** [comment]
It’s not there because the button can’t be injected anyway (the giant yellow banner)

**Comment by TheBlueKingLP** [comment]
> It’s not there because the button can’t be injected anyway (the giant yellow banner)

It still attempts to inject the button though?
```
main-1  | [08:11:26] [DBG] [51] IntroSkipper.Plugin: Reading index.html from /usr/share/jellyfin/web/index.html
main-1  | [08:11:27] [ERR] [51] IntroSkipper.Plugin: Failed to add skip button to web interface. See https://github.com/intro-skipper/intro-skipper/wiki/Troubleshooting#skip-button-is-not-visible for the most common issues. Error: System.UnauthorizedAccessException: Access to the path '/usr/share/jellyfin/web/index.html' is denied.
main-1  |  ---> System.IO.IOException: Permission denied
main-1  |    --- End of inner exception stack trace ---
main-1  |    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
main-1  |    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
main-1  |    at System.IO.File.WriteToFile(String path, FileMode mode, String contents, Encoding encoding)
main-1  |    at IntroSkipper.Plugin.InjectSkipButton(String webPath)
main-1  |    at IntroSkipper.Plugin..ctor(IApplicationHost applicationHost, IApplicationPaths applicationPaths, IXmlSerializer xmlSerializer, IServerConfigurationManager serverConfiguration, ILibraryManager libraryManager, IItemRepository itemRepository, ILogger`1 logger)
```

**Comment by AbandonedCart** [comment]
It attempts to **determine** if injection is possible.

**Comment by rlauuzo** [comment]
Go to Config > Plugins > Configurations > introskipper.xml and set <SkipButtonVisible> to false

**Comment by AbandonedCart** [comment]
Rather than having to manually edit configuration files, the next release will still allow disabling the button even when it can't be injected. The end result will be **identical** but without the error message to cause any confusion.

**Comment by TheBlueKingLP** [comment]
> Rather than having to manually edit configuration files, the next release will still allow disabling the button even when it can't be injected. The end result will be **identical** but without the error message to cause any confusion.

Updated to the latest version 1.10.10.2 with the `Show skip intro / credit button` checkbox unchecked, however the error still appears on every startup
```
main-1  | [19:09:29] [DBG] [1] IntroSkipper.Plugin: Reading index.html from /usr/share/jellyfin/web/index.html
main-1  | [19:09:29] [ERR] [1] IntroSkipper.Plugin: Failed to add skip button to web interface. See https://github.com/intro-skipper/intro-skipper/wiki/Troubleshooting#skip-button-is-not-visible for the most common issues. Error: System.UnauthorizedAccessException: Access to the path '/usr/share/jellyfin/web/index.html' is denied.
main-1  |  ---> System.IO.IOException: Permission denied
main-1  |    --- End of inner exception stack trace ---
main-1  |    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
main-1  |    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
main-1  |    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
main-1  |    at System.IO.File.OpenHandle(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
main-1  |    at System.IO.File.WriteToFile(String path, FileMode mode, String contents, Encoding encoding)
main-1  |    at IntroSkipper.Plugin.InjectSkipButton(String webPath)
main-1  |    at IntroSkipper.Plugin..ctor(IApplicationHost applicationHost, IApplicationPaths applicationPaths, IXmlSerializer xmlSerializer, IServerConfigurationManager serverConfiguration, ILibraryManager libraryManager, IItemRepository itemRepository, ILogger`1 logger)
main-1  | Trailing option(s) found in the command: may be ignored.
main-1  | Trailing option(s) found in the command: may be ignored.
main-1  | Trailing option(s) found in the command: may be ignored.
main-1  | Trailing option(s) found in the command: may be ignored.
main-1  | [19:09:30] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Intro Skipper 1.10.10.2
```

**Comment by AbandonedCart** [comment]
Reset the server

**Comment by TheBlueKingLP** [comment]
> Reboot the server

I have even did a `docker compose down && docker compose up -d` but the same error persists.

**Comment by jumoog** [comment]
The error is good! It means it does not have permission to inject our javascript code! So no modification is possible. The inject was needed for 10.9. But this is not a problem in 10.10 as you can use the new official way. Just ignore the error message in the meantime. I'll change the code to make it look less dramatic.
