### ISSUE TITLE
[Bug]: JF 10.10.x keeps losing settings

### ISSUE THREAD

**Issue by michael-zock** [intro-skipper/intro-skipper#374]
### Self service debugging

- [X] I use Jellyfin 10.10.1 (or newer) and my permissions are correct

### Describe the bug

For some reason, on 10.10.x the options for "Automatically Scan Intros" and "Automatically Scan Credits" occasionally get unset and now there's even the below error that shows up in the logs even though there's no option in the plugin settings to  select individual libraries.

### Jellyfin install method

Official Windows amd64 exe

### Container image/tag or Jellyfin version

10.10.1

### Operating System

Windows 11 Pro

### Support Bundle

```shell
* Jellyfin version: 10.10.1
* Plugin version: 1.10.10+71768972e5ef
* Queue contents: 23720 episodes, 1502 seasons
* Warnings: `InvalidChromaprintFingerprint`
* FFmpeg: `okay`

FFmpeg version:

ffmpeg version 7.0.2-Jellyfin Copyright (c) 2000-2024 the FFmpeg developers
built with clang version 18.1.8
configuration: --cc=clang --pkg-config-flags=--static --extra-cflags=-I/clang64/ffbuild/include --extra-ldflags=-L/clang64/ffbuild/lib --prefix=/clang64/ffbuild/jellyfin-ffmpeg --extra-version=Jellyfin --disable-ffplay --disable-debug --disable-doc --disable-sdl2 --disable-ptx-compression --enable-lto=thin --enable-gpl --enable-version3 --enable-schannel --enable-iconv --enable-libxml2 --enable-zlib --enable-lzma --enable-gmp --enable-chromaprint --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libharfbuzz --enable-libass --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libwebp --enable-libvpx --enable-libzimg --enable-libx264 --enable-libx265 --enable-libsvtav1 --enable-libdav1d --enable-libfdk-aac --enable-opencl --enable-dxva2 --enable-d3d11va --enable-d3d12va --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
libavutil      59.  8.100 / 59.  8.100
libavcodec     61.  3.100 / 61.  3.100
libavformat    61.  1.100 / 61.  1.100
libavdevice    61.  1.100 / 61.  1.100
libavfilter    10.  1.100 / 10.  1.100
libswscale      8.  1.100 /  8.  1.100
libswresample   5.  1.100 /  5.  1.100
libpostproc    58.  1.100 / 58.  1.100
```
```


### Jellyfin logs

```shell
[2024-11-05 15:40:19.067 +01:00] [ERR] [58] IntroSkipper.Services.Entrypoint: Error in RunAnalysisAsync
IntroSkipper.Data.FingerprintException: No libraries selected for analysis. Please visit the plugin settings to configure.
   at IntroSkipper.ScheduledTasks.BaseItemAnalyzerTask.AnalyzeItems(IProgress`1 progress, CancellationToken cancellationToken, IReadOnlyCollection`1 seasonsToAnalyze)
   at IntroSkipper.Services.Entrypoint.PerformAnalysisAsync()
   at IntroSkipper.Services.Entrypoint.RunAnalysisAsync()
```

**Comment by AbandonedCart** [comment]
Check if you have a ConfusedPolarBear XML file in the plugins\configurations folder and, if so, delete it.

**Comment by michael-zock** [comment]
Thanks!
I've deleted it and will now have to keep an eye on the server whether that fixed it for good.

**Comment by AbandonedCart** [comment]
We moved to a different package and it appears the automated transfer struggles on windows. It shouldn't reappear, though.
