### ISSUE TITLE
[Bug]: System.ArgumentOutOfRangeException: mediaSegment.EndTicks error message

### ISSUE THREAD

**Issue by boydaihungst** [intro-skipper/intro-skipper#381]
### Self service debugging

- [X] I use Jellyfin 10.10.2 (or newer) and my permissions are correct

### Describe the bug

This `System.ArgumentOutOfRangeException: mediaSegment.EndTicks...` error messages are shown up every time it scans for the credit, for many shows. Check the logs below.

### Jellyfin install method

ubuntu apt

### Container image/tag or Jellyfin version

jellyfin 10.10.2

### Operating System

Ubuntu 24.04.1 LTS x86_64

### Support Bundle

```shell
* Jellyfin version: 10.10.2
* Plugin version: 1.10.10+f275e188da52
* Queue contents: 12772 episodes, 850 seasons
* Warnings: `None`
* FFmpeg: `okay`

FFmpeg version:

ffmpeg version 7.0.2-Jellyfin Copyright (c) 2000-2024 the FFmpeg developers
built with gcc 13 (Ubuntu 13.2.0-23ubuntu4)
configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto=auto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-opencl --enable-libdrm --enable-libxml2 --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libharfbuzz --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libsvtav1 --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-vaapi --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
libavutil      59.  8.100 / 59.  8.100
libavcodec     61.  3.100 / 61.  3.100
libavformat    61.  1.100 / 61.  1.100
libavdevice    61.  1.100 / 61.  1.100
libavfilter    10.  1.100 / 10.  1.100
libswscale      8.  1.100 /  8.  1.100
libswresample   5.  1.100 /  5.  1.100
libpostproc    58.  1.100 / 58.  1.100
```

### Jellyfin logs

```shell
Nov 19 00:21:02 ubuntu-server jellyfin[367642]: [00:21:02] [INF] [Mode: Introduction] Analyzing 13 files from Uncle from Another World season 1
Nov 19 00:21:03 ubuntu-server jellyfin[367642]: [00:21:03] [ERR] Error processing episode cbafbd8f-6981-45a9-e11b-6ea98984cb29
Nov 19 00:21:03 ubuntu-server jellyfin[367642]: System.ArgumentOutOfRangeException: mediaSegment.EndTicks ('2872584000') must be greater than or equal to '2877440000'. (Parameter 'mediaSegment.EndTicks')
Nov 19 00:21:03 ubuntu-server jellyfin[367642]: Actual value was 2872584000.
Nov 19 00:21:03 ubuntu-server jellyfin[367642]:    at System.ArgumentOutOfRangeException.ThrowLess[T](T value, T other, String paramName)
Nov 19 00:21:03 ubuntu-server jellyfin[367642]:    at Jellyfin.Server.Implementations.MediaSegments.MediaSegmentManager.CreateSegmentAsync(MediaSegmentDto mediaSegment, String segmentProviderId)
Nov 19 00:21:03 ubuntu-server jellyfin[367642]:    at IntroSkipper.Manager.MediaSegmentUpdateManager.UpdateMediaSegmentsAsync(IReadOnlyList`1 episodes, CancellationTokencancellationToken)

Nov 19 00:21:09 ubuntu-server jellyfin[367642]: [00:21:09] [INF] [Mode: Credits] Analyzing 12 files from Wonder Egg Priority season 1
Nov 19 00:21:09 ubuntu-server jellyfin[367642]: [00:21:09] [ERR] Error processing episode b8f56936-9ba9-bc6b-f049-2a664b057b80
Nov 19 00:21:09 ubuntu-server jellyfin[367642]: System.ArgumentOutOfRangeException: mediaSegment.EndTicks ('1014910000') must be greater than or equal to '1027840000'. (Parameter 'mediaSegment.EndTicks')
Nov 19 00:21:09 ubuntu-server jellyfin[367642]: Actual value was 1014910000.
Nov 19 00:21:09 ubuntu-server jellyfin[367642]:    at System.ArgumentOutOfRangeException.ThrowLess[T](T value, T other, String paramName)
Nov 19 00:21:09 ubuntu-server jellyfin[367642]:    at Jellyfin.Server.Implementations.MediaSegments.MediaSegmentManager.CreateSegmentAsync(MediaSegmentDto mediaSegment, String segmentProviderId)
Nov 19 00:21:09 ubuntu-server jellyfin[367642]:    at IntroSkipper.Manager.MediaSegmentUpdateManager.UpdateMediaSegmentsAsync(IReadOnlyList`1 episodes, CancellationTokencancellationToken)
```

**Comment by mihawk90** [comment]
Can you get an `mkvinfo` output from one of the affected files? If it's not an MKV you can also use `ffprobe`.

From my testing (unrelated to IntroSkipper) this is caused by chapter markers that are for one reason or another set after the total runtime of the video.

**Comment by boydaihungst** [comment]
Here are the logs. I've never enabled chapter images marker, only trickplay.
![image](https://github.com/user-attachments/assets/95e74463-20da-4c36-84cf-dc199dc60adc)

```
Nov 19 00:21:05 ubuntu-server jellyfin[367642]: [00:21:05] [INF] [Mode: Credits] Analyzing 26 files from Valkyria Chronicles season 1
Nov 19 00:21:05 ubuntu-server jellyfin[367642]: [00:21:05] [INF] [Mode: Introduction] Analyzing 26 files from Valkyria Chronicles season 1
Nov 19 00:21:05 ubuntu-server jellyfin[367642]: [00:21:05] [ERR] Error processing episode b40b534f-3611-283c-2d6e-534fcf5c88ca
Nov 19 00:21:05 ubuntu-server jellyfin[367642]: System.ArgumentOutOfRangeException: mediaSegment.EndTicks ('1182183000') must be greater than or equal to '1202097999'. (Parameter 'mediaSegment.EndTicks')
Nov 19 00:21:05 ubuntu-server jellyfin[367642]: Actual value was 1182183000.
Nov 19 00:21:05 ubuntu-server jellyfin[367642]:    at System.ArgumentOutOfRangeException.ThrowLess[T](T value, T other, String paramName)
Nov 19 00:21:05 ubuntu-server jellyfin[367642]:    at Jellyfin.Server.Implementations.MediaSegments.MediaSegmentManager.CreateSegmentAsync(MediaSegmentDto mediaSegment,String segmentProviderId)
Nov 19 00:21:05 ubuntu-server jellyfin[367642]:    at IntroSkipper.Manager.MediaSegmentUpdateManager.UpdateMediaSegmentsAsync(IReadOnlyList`1 episodes, CancellationToken cancellationToken)
```

```
+ EBML head
|+ EBML version: 1
|+ EBML read version: 1
|+ Maximum EBML ID length: 4
|+ Maximum EBML size length: 8
|+ Document type: matroska
|+ Document type version: 2
|+ Document type read version: 2
+ Segment: size 468385952
|+ Seek head (subentries will be skipped)
|+ EBML void: size 4013
|+ Segment information
| + Timestamp scale: 1000000
| + Multiplexing application: libebml v1.0.0 + libmatroska v1.0.0
| + Writing application: mkvmerge v4.4.0 ('Die Wiederkehr') built on Oct 31 2010 21:52:48
| + Duration: 00:20:39.655000000
| + Date: 2011-06-21 17:11:50 UTC
| + Title: Valkyria Chronicles 08
| + Segment UID: 0xa9 0xbf 0x98 0x29 0x9a 0x07 0x23 0x28 0xbe 0x3a 0x32 0xe9 0x09 0xa4 0x82 0xe3
|+ Tracks
| + Track
|  + Track number: 1 (track ID for mkvmerge & mkvextract: 0)
|  + Track UID: 1795067298
|  + Track type: video
|  + "Lacing" flag: 0
|  + Minimum cache: 1
|  + Codec ID: V_MPEG4/ISO/AVC
|  + Codec's private data: size 44 (H.264 profile: High @L5.1)
|  + Default duration: 00:00:00.041708333 (23.976 frames/fields per second for a video track)
|  + Language: und
|  + Name: Valkyria Chronicles 08
|  + Video track
|   + Pixel width: 1920
|   + Pixel height: 1080
|   + Display width: 1920
|   + Display height: 1080
| + Track
|  + Track number: 2 (track ID for mkvmerge & mkvextract: 1)
|  + Track UID: 3387518631
|  + Track type: audio
|  + Codec ID: A_FLAC
|  + Codec's private data: size 154
|  + Default duration: 00:00:00.085333333 (11.719 frames/fields per second for a video track)
|  + Language: jpn
|  + Name: 2.0 FLAC
|  + Audio track
|   + Sampling frequency: 48000
|   + Channels: 2
|   + Bit depth: 16
| + Track
|  + Track number: 3 (track ID for mkvmerge & mkvextract: 2)
|  + Track UID: 1411012993
|  + Track type: subtitles
|  + "Lacing" flag: 0
|  + Codec ID: S_TEXT/ASS
|  + Codec's private data: size 1593
|  + Name: English
|+ EBML void: size 1120
|+ Attachments
| + Attached
|  + File name: albr55w.ttf
|  + MIME type: application/x-truetype-font
|  + File data: size 92344
|  + File UID: 2680557751
| + Attached
|  + File name: Berkeley-Oldstyle-Bold.ttf
|  + MIME type: application/x-truetype-font
|  + File data: size 50960
|  + File UID: 2273771423
| + Attached
|  + File name: CALIBRI.TTF
|  + MIME type: application/x-truetype-font
|  + File data: size 352736
|  + File UID: 1407846072
| + Attached
|  + File name: SEVEMFBR.TTF
|  + MIME type: application/x-truetype-font
|  + File data: size 23904
|  + File UID: 3047689884
|+ Chapters
| + Edition entry
|  + Edition flag default: 1
|  + Edition flag ordered: 1
|  + Edition UID: 2275424240168272589
|  + Edition flag hidden: 0
|  + Chapter atom
|   + Chapter time start: 00:00:00.000000000
|   + Chapter time end: 00:01:29.965000000
|   + Chapter UID: 8405755852218338372
|   + Chapter segment UID: length 16, data: 0xab 0x79 0x85 0x3f 0x78 0x64 0x08 0xf6 0x98 0x64 0x84 0xc4 0xc5 0xb9 0x19 0x5e
|   + Chapter flag hidden: 0
|   + Chapter flag enabled: 1
|   + Chapter display
|    + Chapter string: Opening
|    + Chapter language: eng
|  + Chapter atom
|   + Chapter time start: 00:00:00.000000000
|   + Chapter time end: 00:20:09.875000000
|   + Chapter UID: 2152312356670759831
|   + Chapter flag hidden: 0
|   + Chapter flag enabled: 1
|   + Chapter display
|    + Chapter string: Episode
|    + Chapter language: eng
|  + Chapter atom
|   + Chapter time start: 00:00:00.000000000
|   + Chapter time end: 00:01:29.923000000
|   + Chapter UID: 11927957420107533336
|   + Chapter segment UID: length 16, data: 0x83 0xfa 0xa4 0x97 0x2a 0xa1 0x87 0x7c 0xbc 0x22 0xd0 0x74 0xb9 0x65 0xa3 0x83
|   + Chapter flag hidden: 0
|   + Chapter flag enabled: 1
|   + Chapter display
|    + Chapter string: Ending
|    + Chapter language: und
|  + Chapter atom
|   + Chapter time start: 00:20:09.917000000
|   + Chapter time end: 00:20:39.613000000
|   + Chapter UID: 10081834910456000126
|   + Chapter flag hidden: 0
|   + Chapter flag enabled: 1
|   + Chapter display
|    + Chapter string: Preview
|    + Chapter language: und
|+ EBML void: size 101
|+ Cluster
```
---------------------ffprobe---------------------
```
ffprobe version 6.1.1-3ubuntu5 Copyright (c) 2007-2023 the FFmpeg developers
  built with gcc 13 (Ubuntu 13.2.0-23ubuntu3)
  configuration: --prefix=/usr --extra-version=3ubuntu5 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --disable-omx --enable-gnutls --enable-libaom --enable-libass --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libglslang --enable-libgme --enable-libgsm --enable-libharfbuzz --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr--enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-openal --enable-opencl --enable-opengl --disable-sndio --enable-libvpl --disable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-ladspa --enable-libbluray --enable-libjack --enable-libpulse --enable-librabbitmq --enable-librist --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libx264 --enable-libzmq --enable-libzvbi --enable-lv2 --enable-sdl2 --enable-libplacebo --enable-librav1e --enable-pocketsphinx --enable-librsvg --enable-libjxl --enable-shared
  libavutil      58. 29.100 / 58. 29.100
  libavcodec     60. 31.102 / 60. 31.102
  libavformat    60. 16.100 / 60. 16.100
  libavdevice    60.  3.100 / 60.  3.100
  libavfilter     9. 12.100 /  9. 12.100
  libswscale      7.  5.100 /  7.  5.100
  libswresample   4. 12.100 /  4. 12.100
  libpostproc    57.  3.100 / 57.  3.100
[matroska,webm @ 0x5c495a6cbc00] Invalid value of WAVEFORMATEXTENSIBLE_CHANNEL_MASK
Input #0, matroska,webm, from '/mnt/hdd/Anime/Valkyria Chronicles (2009) [tvdbid-87851]/Season 01/Valkyria Chronicles - S01E08.mkv':
  Metadata:
    title           : Valkyria Chronicles 08
    encoder         : libebml v1.0.0 + libmatroska v1.0.0
    creation_time   : 2011-06-21T17:11:50.000000Z
  Duration: 00:20:39.66, start: 0.000000, bitrate: 3022 kb/s
  Chapters:
    Chapter #0:0: start 0.000000, end 89.965000
      Metadata:
        title           : Opening
    Chapter #0:1: start 0.000000, end 1209.875000
      Metadata:
        title           : Episode
    Chapter #0:2: start 0.000000, end 89.923000
      Metadata:
        title           : Ending
    Chapter #0:3: start 1209.917000, end 1239.613000
      Metadata:
        title           : Preview
  Stream #0:0: Video: h264 (High), yuv420p(progressive), 1920x1080, SAR 1:1 DAR 16:9, 23.98 fps, 23.98 tbr, 1k tbn (default)
    Metadata:
      title           : Valkyria Chronicles 08
  Stream #0:1(jpn): Audio: flac, 48000 Hz, stereo, s16 (default)
    Metadata:
      title           : 2.0 FLAC
  Stream #0:2(eng): Subtitle: ass (default)
    Metadata:
      title           : English
  Stream #0:3: Attachment: ttf
    Metadata:
      filename        : albr55w.ttf
      mimetype        : application/x-truetype-font
  Stream #0:4: Attachment: ttf
    Metadata:
      filename        : Berkeley-Oldstyle-Bold.ttf
      mimetype        : application/x-truetype-font
  Stream #0:5: Attachment: ttf
    Metadata:
      filename        : CALIBRI.TTF
      mimetype        : application/x-truetype-font
  Stream #0:6: Attachment: ttf
    Metadata:
      filename        : SEVEMFBR.TTF
      mimetype        : application/x-truetype-font
Unsupported codec with id 98304 for input stream 3
Unsupported codec with id 98304 for input stream 4
Unsupported codec with id 98304 for input stream 5
Unsupported codec with id 98304 for input stream 6
```

**Comment by rlauuzo** [comment]
Could you check the Timestamp Editor at the bottom of the settings page to see if the intro and credits times are displayed?

**Comment by jumoog** [comment]
When you play the file, can you watch it to the end? I have corrupted mkv files that pretend to be much longer than they are. And I can only watch the first half of it because there is no video/audio for the second part.

**Comment by jumoog** [comment]
```
Opening 00:00:00.000000000 - 00:01:29.965000000
Episode 00:00:00.000000000 - 00:20:09.875000000
Ending  00:00:00.000000000 - 00:01:29.923000000
Preview 00:20:09.917000000 - 00:20:39.613000000
```

**Comment by boydaihungst** [comment]
@rlauuzo If you mean this. There is only intro times.
![image](https://github.com/user-attachments/assets/b23f6b34-628a-41e8-9db0-f9246d29a351)

**Comment by boydaihungst** [comment]
@jumoog Yes I can watch it to the end without problem. Ignore my custom theme.
![image](https://github.com/user-attachments/assets/3c18c350-4257-4f14-98c5-7eedfe86d89a)

**Comment by jumoog** [comment]
> @rlauuzo If you mean this. There is only intro times. ![image](https://private-user-images.githubusercontent.com/38396158/387567713-b23f6b34-628a-41e8-9db0-f9246d29a351.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwMDYzMTEsIm5iZiI6MTczMjAwNjAxMSwicGF0aCI6Ii8zODM5NjE1OC8zODc1Njc3MTMtYjIzZjZiMzQtNjI4YS00MWU4LTlkYjAtZjkyNDZkMjlhMzUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE5VDA4NDY1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2OGIzNzllMGMzN2FjN2JlMDQ4NTVmYWU4NzM3Nzc1YjE5ZmUzYzc3MjM5YjdmYTc1ZDczNmQ1OTJiMDY2NDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.OXNttBIeB5CG1Ri2Tir6qni1WChVUn8PDGZnXanLk1I)

Intro should start at 0

**Comment by rlauuzo** [comment]
Try using the 'Erase All Timestamps for This Season' option, then initiate a new scan.

**Comment by intro-skipper-dev** [comment]
I think the problem is the chapter layout. All Chapters start at 0 besides `Preview`.
And `Opening` and `Ending` are overlapping.

**Comment by boydaihungst** [comment]
@jumoog: Actually, this episode doesn't have an intro or outro (the preview section has the narrator's dialogues). There's a short music track at 120 seconds, so it considers as intro is understandable.

@rlauuzo: These are the logs after ticking "Erase cached fingerprint files," "Erase all timestamps for this season," and then rescanning.
![image](https://github.com/user-attachments/assets/365a8ede-ec2e-44e1-97ef-be1b60468b84)

```
Nov 19 09:43:40 ubuntu-server jellyfin[382561]: [09:43:40] [INF] [Mode: Credits] Analyzing 26 files from Valkyria Chronicles season 1
Nov 19 09:43:40 ubuntu-server jellyfin[718018]: [matroska,webm @ 0x5c778312a840] Invalid value of WAVEFORMATEXTENSIBLE_CHANNEL_MASK
Nov 19 09:43:41 ubuntu-server jellyfin[718033]: [matroska,webm @ 0x6178335df840] Invalid value of WAVEFORMATEXTENSIBLE_CHANNEL_MASK
Nov 19 09:43:42 ubuntu-server jellyfin[718049]: [matroska,webm @ 0x55831bea4840] Invalid value of WAVEFORMATEXTENSIBLE_CHANNEL_MASK
Nov 19 09:43:42 ubuntu-server jellyfin[718064]: [matroska,webm @ 0x62111226e840] Invalid value of WAVEFORMATEXTENSIBLE_CHANNEL_MASK
Nov 19 09:43:43 ubuntu-server jellyfin[718079]: [matroska,webm @ 0x650d25585840] Invalid value of WAVEFORMATEXTENSIBLE_CHANNEL_MASK
Nov 19 09:43:43 ubuntu-server jellyfin[718094]: [matroska,webm @ 0x5c03a1c24840] Invalid value of WAVEFORMATEXTENSIBLE_CHANNEL_MASK
Nov 19 09:43:44 ubuntu-server jellyfin[718109]: [matroska,webm @ 0x5b98563cb840] Invalid value of WAVEFORMATEXTENSIBLE_CHANNEL_MASK
Nov 19 09:43:45 ubuntu-server jellyfin[718177]: [matroska,webm @ 0x61cfca7ce840] Invalid value of WAVEFORMATEXTENSIBLE_CHANNEL_MASK
Nov 19 09:43:45 ubuntu-server jellyfin[718196]: [matroska,webm @ 0x61e28293a840] Invalid value of WAVEFORMATEXTENSIBLE_CHANNEL_MASK
Nov 19 09:43:46 ubuntu-server jellyfin[718211]: [matroska,webm @ 0x5b2602a2d840] Invalid value of WAVEFORMATEXTENSIBLE_CHANNEL_MASK
Nov 19 09:43:47 ubuntu-server jellyfin[718226]: [matroska,webm @ 0x64105ae67840] Invalid value of WAVEFORMATEXTENSIBLE_CHANNEL_MASK
Nov 19 09:43:47 ubuntu-server jellyfin[718252]: [matroska,webm @ 0x5f488debb840] Invalid value of WAVEFORMATEXTENSIBLE_CHANNEL_MASK
Nov 19 09:43:48 ubuntu-server jellyfin[718274]: [matroska,webm @ 0x55a881367840] Invalid value of WAVEFORMATEXTENSIBLE_CHANNEL_MASK
Nov 19 09:43:48 ubuntu-server jellyfin[718289]: [matroska,webm @ 0x5e46c03c7840] Invalid value of WAVEFORMATEXTENSIBLE_CHANNEL_MASK
Nov 19 09:43:48 ubuntu-server jellyfin[718289]: [matroska,webm @ 0x5e46c03c7840] Could not find codec parameters for stream 4 (Attachment: none): unknown codec
Nov 19 09:43:48 ubuntu-server jellyfin[718289]: Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
Nov 19 09:43:49 ubuntu-server jellyfin[718304]: [matroska,webm @ 0x63bc0b622840] Invalid value of WAVEFORMATEXTENSIBLE_CHANNEL_MASK
Nov 19 09:43:49 ubuntu-server jellyfin[718304]: [matroska,webm @ 0x63bc0b622840] Could not find codec parameters for stream 4 (Attachment: none): unknown codec
Nov 19 09:43:49 ubuntu-server jellyfin[718304]: Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
Nov 19 09:43:49 ubuntu-server jellyfin[718319]: [matroska,webm @ 0x582ee791d840] Invalid value of WAVEFORMATEXTENSIBLE_CHANNEL_MASK
Nov 19 09:43:49 ubuntu-server jellyfin[718319]: [matroska,webm @ 0x582ee791d840] Could not find codec parameters for stream 4 (Attachment: none): unknown codec
Nov 19 09:43:49 ubuntu-server jellyfin[718319]: Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
Nov 19 09:43:50 ubuntu-server jellyfin[718335]: [matroska,webm @ 0x63968aa5e840] Invalid value of WAVEFORMATEXTENSIBLE_CHANNEL_MASK
Nov 19 09:43:50 ubuntu-server jellyfin[718335]: [matroska,webm @ 0x63968aa5e840] Could not find codec parameters for stream 4 (Attachment: none): unknown codec
Nov 19 09:43:50 ubuntu-server jellyfin[718335]: Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
Nov 19 09:43:51 ubuntu-server jellyfin[718350]: [matroska,webm @ 0x616081982840] Invalid value of WAVEFORMATEXTENSIBLE_CHANNEL_MASK
Nov 19 09:43:51 ubuntu-server jellyfin[718350]: [matroska,webm @ 0x616081982840] Could not find codec parameters for stream 4 (Attachment: none): unknown codec
Nov 19 09:43:51 ubuntu-server jellyfin[718350]: Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
Nov 19 09:43:51 ubuntu-server jellyfin[718365]: [matroska,webm @ 0x5d72ae7ba840] Invalid value of WAVEFORMATEXTENSIBLE_CHANNEL_MASK
Nov 19 09:43:51 ubuntu-server jellyfin[718365]: [matroska,webm @ 0x5d72ae7ba840] Could not find codec parameters for stream 4 (Attachment: none): unknown codec
Nov 19 09:43:51 ubuntu-server jellyfin[718365]: Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
...
```

**Comment by intro-skipper-dev** [comment]
But `System.ArgumentOutOfRangeException: mediaSegment.EndTick` still happens?

**Comment by boydaihungst** [comment]
Not more xD. Should I erase global timstamps?

**Comment by intro-skipper-dev** [comment]
> Not more xD. Should I erase global timstamps?

No. Thank you for the clarification. We need to investigate what the problem is.

**Comment by jumoog** [comment]
Any news? I can't reproduce the problem. Does this still happens in the newest version?

**Comment by boydaihungst** [comment]
This cmd return no entries so I guess it's not happend anymore.

`journalctl -e -g "ArgumentOutOfRangeException" -u jellyfin.service --lines 1000000000`
