### ISSUE TITLE
[Bug]: No libraries selected for analysis. Please visit the plugin settings to configure.

### ISSUE THREAD

**Issue by TheColin21** [intro-skipper/intro-skipper#417]
### Self service debugging

- [X] I use Jellyfin 10.10.3 (or newer) and my permissions are correct

### Describe the bug

I see the error message below in my Jellyfin log pretty often.

IntroSkipper seems to work for all my shows and I cannot find a library selection in the plugin settings and as this is logged as an actual error I thought I'd report it.

### Jellyfin install method

Docker

### Container image/tag or Jellyfin version

lscr.io/linuxserver/jellyfin:latest

### Operating System

TrueNAS 24.10

### Support Bundle

```shell
* Jellyfin version: 10.10.3
* Plugin version: 1.10.10+1048eaf26d7e
* Queue contents: 1450 episodes, 91 seasons
* Warnings: `None`
* FFmpeg: `okay`

FFmpeg version:

ffmpeg version 7.0.2-Jellyfin Copyright (c) 2000-2024 the FFmpeg developers
built with gcc 13 (Ubuntu 13.2.0-23ubuntu4)
configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto=auto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-opencl --enable-libdrm --enable-libxml2 --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libharfbuzz --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libsvtav1 --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-vaapi --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
libavutil      59.  8.100 / 59.  8.100
libavcodec     61.  3.100 / 61.  3.100
libavformat    61.  1.100 / 61.  1.100
libavdevice    61.  1.100 / 61.  1.100
libavfilter    10.  1.100 / 10.  1.100
libswscale      8.  1.100 /  8.  1.100
libswresample   5.  1.100 /  5.  1.100
libpostproc    58.  1.100 / 58.  1.100
```
```


### Jellyfin logs

```shell
IntroSkipper.Data.FingerprintException: No libraries selected for analysis. Please visit the plugin settings to configure.
   at IntroSkipper.ScheduledTasks.BaseItemAnalyzerTask.AnalyzeItemsAsync(IProgress`1 progress, CancellationToken cancellationToken, IReadOnlyCollection`1 seasonsToAnalyze)
   at IntroSkipper.Services.Entrypoint.PerformAnalysisAsync()
   at IntroSkipper.Services.Entrypoint.RunAnalysisAsync()
```

**Comment by Hello-World-Traveler** [comment]
Go to `/web/#/configurationpage?name=Intro Skipper`  and select Limit analysis to the following libraries or  Enable analysis for all libraries containing television episodes

**Comment by TheColin21** [comment]
Sorry I overlooked that.
It is already set to `Enable analysis for all libraries containing television episodes`.
So it should work right?

**Comment by englut** [comment]
I am having this issue too. 

```
[2024-12-17 14:13:58.335 -08:00] [INF] Scheduled Task is starting
[2024-12-17 14:13:58.335 -08:00] [INF] Limiting analysis to the following libraries: ["Series"]
[2024-12-17 14:13:58.336 -08:00] [INF] Running enqueue of items in library "Series"
[2024-12-17 14:13:58.336 -08:00] [ERR] Error executing Scheduled Task
IntroSkipper.Data.FingerprintException: No libraries selected for analysis. Please visit the plugin settings to configure.
   at IntroSkipper.ScheduledTasks.BaseItemAnalyzerTask.AnalyzeItemsAsync(IProgress`1 progress, CancellationToken cancellationToken, IReadOnlyCollection`1 seasonsToAnalyze)
   at IntroSkipper.ScheduledTasks.DetectSegmentsTask.ExecuteAsync(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[2024-12-17 14:13:58.337 -08:00] [INF] "Detect and Analyze Media Segments" Failed after 0 minute(s) and 0 seconds
```

**Comment by englut** [comment]
I am having this issue too. 

```
[2024-12-17 14:13:58.335 -08:00] [INF] Scheduled Task is starting
[2024-12-17 14:13:58.335 -08:00] [INF] Limiting analysis to the following libraries: ["Media"]
[2024-12-17 14:13:58.336 -08:00] [INF] Running enqueue of items in library "Media"
[2024-12-17 14:13:58.336 -08:00] [ERR] Error executing Scheduled Task
IntroSkipper.Data.FingerprintException: No libraries selected for analysis. Please visit the plugin settings to configure.
   at IntroSkipper.ScheduledTasks.BaseItemAnalyzerTask.AnalyzeItemsAsync(IProgress`1 progress, CancellationToken cancellationToken, IReadOnlyCollection`1 seasonsToAnalyze)
   at IntroSkipper.ScheduledTasks.DetectSegmentsTask.ExecuteAsync(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[2024-12-17 14:13:58.337 -08:00] [INF] "Detect and Analyze Media Segments" Failed after 0 minute(s) and 0 seconds
```

You can clearly see in my log that there's a library selected (`Media`), and intro skipper still says there's no libraries selected. I am running the latest Jellyfin (10.10.3)  and latest Intro Skipper (1.10.10.12).

I'm running Jellyfin via docker. Using `linuxserver` docker image. With the environment variables: 
```
PUID=1000
PGID=1000
DOCKER_MODS=linuxserver/mods:jellyfin-opencl-intel|ghcr.io/intro-skipper/intro-skipper-docker-mod
```

**Comment by Hello-World-Traveler** [comment]
```
Error in RunAnalysisAsync
IntroSkipper.Data.FingerprintException: No libraries selected for analysis. Please visit the plugin settings to configure.
   at IntroSkipper.ScheduledTasks.BaseItemAnalyzerTask.AnalyzeItemsAsync(IProgress`1 progress, CancellationToken cancellationToken, IReadOnlyCollection`1 seasonsToAnalyze)
   at IntroSkipper.Services.Entrypoint.PerformAnalysisAsync()
   at IntroSkipper.Services.Entrypoint.RunAnalysisAsync()
```
It seems I also get this as well but I believe it's working.

```
Initiating automatic analysis task
[INF] Limiting analysis to the following libraries
```

**Comment by rlauuzo** [comment]
You can try enabling the option 'Display specials within seasons they aired in' under the library's Display Settings. After that, perform a metadata refresh with the 'Replace all metadata' option.

**Comment by Hello-World-Traveler** [comment]
Already enabled. 
The error is  not something I've noticed before.

**Comment by AbandonedCart** [comment]
@Hello-World-Traveler Did you also perform a metadata refresh with the 'Replace all metadata' option?

**Comment by Hello-World-Traveler** [comment]
Not within the last two weeks. About 2 weeks I did a replacement off all metadata.

@englut @TheColin21 Have you done this yet?

**Comment by englut** [comment]
I noticed something was weird/off about my TV show library (something about the library path being incorrect). so I deleted it and re-created it. I made sure to enable all the trickplay options for this new library (the previous one didn't have them enabled). It's scanning now!

**Comment by englut** [comment]
Interesting. the scheduled task runs, but with the automated analysis task this is returned:

```
jellyfin  | [19:22:25] [INF] Initiating automatic analysis task
jellyfin  | [19:22:25] [INF] Limiting analysis to the following libraries: ["Media"]
jellyfin  | [19:22:25] [INF] Running enqueue of items in library Media
jellyfin  | [19:22:25] [ERR] Error in RunAnalysisAsync
jellyfin  | IntroSkipper.Data.FingerprintException: No libraries selected for analysis. Please visit the plugin settings to configure.
jellyfin  |    at IntroSkipper.ScheduledTasks.BaseItemAnalyzerTask.AnalyzeItemsAsync(IProgress`1 progress, CancellationToken cancellationToken, IReadOnlyCollection`1 seasonsToAnalyze)
jellyfin  |    at IntroSkipper.Services.Entrypoint.PerformAnalysisAsync()
jellyfin  |    at IntroSkipper.Services.Entrypoint.RunAnalysisAsync()
```

So it's partially fixed only.

**Comment by vajonam** [comment]
I also see this only occurring when new media is added.

**Comment by AbandonedCart** [comment]
> So it's partially fixed only.

I was looking at the wrong issue. Please disregard.

**Comment by Zepmann** [comment]
Had the same issue migrating Jellyfin as an OS package to docker. What worked for me based on hints and tips from previous contributors to this issue:

1. Remove all Intro Skipper plugins (including older versions) from Jellyfin's My Plugins page in the web interface.
2. Manually remove Intro Skipper's .xml configuration file (if it still exists) and all plugin and data directories. For a standard docker installation this would be `config/plugins/configurations/IntroSkipper.xml`, `config/data/introskipper` and `config/plugins/Intro Skipper*`
3. Remove all relevant libraries (to be scanned by Intro Skipper).
4. Add and rescan all relevant libraries. I used all trickplay options aside of 'Save trickplay images next to media', since I like to store trickplay images on fast media and videos on slower, larger media. Rescanning will take a while if you have large libraries.
5. Install Intro Skipper again through Jellyfin's Catalog page. Select the relevant libraries. I would avoid the option to scan all libraries since new libraries could one day be added which should not be automatically scanned by Intro Skipper.
6. Run the Intro Skipper - Detect and Analyze Media Segments scheduled task manually. This will take a while if you have large libraries.
7. Once finished, test if you can skip intro's in your content. Look for shows that have the same intro between different episodes for the best test material.
8. If everything works as expected, don't forget to run the Library - Generate Trickplay Images scheduled task to (re)generate trickplay images if you use non-blocking scan behavior. This task will take a very long time, so it is better to start it early instead of waiting for the next time the task runs on a schedule. Just leave it to do its thing in the background while you enjoy Jellyfin. :smile:

Jellyfin still kept user playback progress for the relevant libraries, even when the libraries were removed and added again.

**Comment by Hello-World-Traveler** [comment]
@Zepmann Off topic I know, when you went from OS to docker, did you copy all the files and map folders to a new location? This is something I plan to do.

**Comment by AbandonedCart** [comment]
@Hello-World-Traveler Attempting to go from direct install to Docker or Docker to direct install doesn't work well with trying to keep the full configuration. Be prepared to rebuild parts. If you use folders for libraries and can handle setting up again, it's better to link the metadata and media, but set up the server fresh. That's how you avoid corrupt libraries.

**Comment by Hello-World-Traveler** [comment]
Thank you for the useful tip. I'll do it this way 😃

**Comment by Zepmann** [comment]
@AbandonedCart and @Hello-World-Traveler 

I was able to keep my existing Jellyfin configuration without issue. However, for perfect compatibility it is in my experience best to rebuild libraries.

My advice is to start Jellyfin in docker "fresh" and kill it. From the path mounted as the configuration volume you'll learn which files of an existing installation are supposed to go where. For existing libraries I opted to mount the relevant volume inside the container using the same path as outside the container (=the same path the Jellyfin OS package used). This combined with a full rebuild of the libraries seemed to have worked for me in keeping my configuration and play status for users.

**Comment by AbandonedCart** [comment]
> I was able to keep my existing Jellyfin configuration without issue. However, for perfect compatibility it is in my experience best to rebuild libraries.

That may have been the case, but it typically causes issues that may not be immediately obvious. For the average person without a lot of time and effort invested in setting up libraries, it's not worth the risk.

**Comment by Zepmann** [comment]
@AbandonedCart, agreed. I just wrote about my experience. My general recommendation would be to start fresh. It can avoid some unexpected headaches with Jellyin in general (what works today does not have to work tomorrow) and plugins in particular (less users, so even less testing of this specific scenario).

In my case I was fully prepared to start fresh again if needed.
