### ISSUE TITLE
[Bug]: New Media Always Returns 0 for All  Segments

### ISSUE THREAD

**Issue by XmnwildX12** [intro-skipper/intro-skipper#424]
### Self service debugging

- [X] I use Jellyfin 10.10.3 (or newer) and my permissions are correct

### Describe the bug

The scan works flawlessly on all items that exist but any new media that comes in always has 0 for everything and will remain as such unless I go in and manually erase all the timestamps for the season. In the log it looks like there is a ffprobe error and then introskipper runs and returns chromaprint returned 0 points and then ffprobe runs again a few seconds later without error. So my guess is ffprobe is running initially prior to the file being completely there and errors out and then completes later when its actually there.

In the first scan it analyzes the show and the secondary automatic scan after ffprobe appears to complete successfully it doesn't. So I don't know if the first run it just added the 0's off the failed scan and that was the end of it?

I have been dealing with this issue for over a month and on my fourth fresh install including a complete OS reinstall, I have tried W10 and W11. I have tried doing a complete reinstall downgrading to 10.9.11 and still continue to run into this issue. I have tried a handful of things with disabling firewall/virus, allowing jellyfin/ffmpeg through the firewall, adding full control permissions for all folders with media and both Jellyfin folders, etc. Running out of ideas to try.

### Jellyfin install method

Windows installer

### Container image/tag or Jellyfin version

10.10.3

### Operating System

Windows 10

### IMDb ID of that TV Series

tt7908628

### Support Bundle

```shell
* Jellyfin version: 10.10.3
* Plugin version: 1.10.10+24619a2b00ad
* Queue contents: 3689 episodes, 307 seasons
* Warnings: `InvalidChromaprintFingerprint`
* FFmpeg: `okay`

FFmpeg version:

ffmpeg version 7.0.2-Jellyfin Copyright (c) 2000-2024 the FFmpeg developers
built with clang version 19.1.3
configuration: --cc=clang --pkg-config-flags=--static --extra-cflags=-I/clang64/ffbuild/include --extra-ldflags=-L/clang64/ffbuild/lib --prefix=/clang64/ffbuild/jellyfin-ffmpeg --extra-version=Jellyfin --disable-ffplay --disable-debug --disable-doc --disable-sdl2 --disable-ptx-compression --enable-lto=thin --enable-gpl --enable-version3 --enable-schannel --enable-iconv --enable-libxml2 --enable-zlib --enable-lzma --enable-gmp --enable-chromaprint --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libharfbuzz --enable-libass --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libwebp --enable-libvpx --enable-libzimg --enable-libx264 --enable-libx265 --enable-libsvtav1 --enable-libdav1d --enable-libfdk-aac --enable-opencl --enable-dxva2 --enable-d3d11va --enable-d3d12va --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
libavutil      59.  8.100 / 59.  8.100
libavcodec     61.  3.100 / 61.  3.100
libavformat    61.  1.100 / 61.  1.100
libavdevice    61.  1.100 / 61.  1.100
libavfilter    10.  1.100 / 10.  1.100
libswscale      8.  1.100 /  8.  1.100
libswresample   5.  1.100 /  5.  1.100
libpostproc    58.  1.100 / 58.  1.100
```
```


### Jellyfin logs

```shell
[2024-12-16 23:29:09.832 -06:00] [INF] [55] Emby.Server.Implementations.IO.LibraryMonitor: "Season 6" ("C:\Media\TV\What We Do in the Shadows\Season 6") will be refreshed.
[2024-12-16 23:29:09.942 -06:00] [INF] [62] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"C:\Media\TV\What We Do in the Shadows\Season 6\What We Do in the Shadows - S06E11 - The Finale WEBDL-1080p.mkv\" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"
[2024-12-16 23:29:10.524 -06:00] [ERR] [88] MediaBrowser.Providers.TV.EpisodeMetadataService: Error in "Probe Provider"
MediaBrowser.Common.FfmpegException: ffprobe failed - streams and format are both null.
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.FFProbeVideoInfo.ProbeVideo[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
[2024-12-16 23:29:12.858 -06:00] [INF] [88] Jellyfin.Plugin.TvMaze.Providers.TvMazeEpisodeImageProvider: [GetImages] Images found for "The Finale": [RemoteImageInfo { ProviderName: "TVmaze", Url: "https://static.tvmaze.com/uploads/images/original_untouched/548/1370170.jpg", ThumbnailUrl: null, Height: null, Width: null, CommunityRating: null, VoteCount: null, Language: "en", Type: Primary, RatingType: Score }]
[2024-12-16 23:29:13.445 -06:00] [INF] [44] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Episode", Name: "The Finale", Path: "", Id: 50f5ba0e-aea4-ed0b-e1ab-11e2764ec570
[2024-12-16 23:29:19.871 -06:00] [INF] [62] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[2024-12-16 23:29:23.460 -06:00] [INF] [29] Trakt.Helpers.LibraryManagerEventsHelper: Timer elapsed - processing queued items
[2024-12-16 23:29:23.464 -06:00] [INF] [29] Trakt.Helpers.LibraryManagerEventsHelper: No movies with event type Remove to process
[2024-12-16 23:29:23.465 -06:00] [INF] [29] Trakt.Helpers.LibraryManagerEventsHelper: No movies with event type Add to process
[2024-12-16 23:29:23.466 -06:00] [INF] [29] Trakt.Helpers.LibraryManagerEventsHelper: No movies with event type Update to process
[2024-12-16 23:29:23.471 -06:00] [INF] [29] Trakt.Helpers.LibraryManagerEventsHelper: No episodes with event type Remove to process
[2024-12-16 23:29:23.472 -06:00] [INF] [29] Trakt.Helpers.LibraryManagerEventsHelper: No episodes with event type Add to process
[2024-12-16 23:29:23.473 -06:00] [INF] [29] Trakt.Helpers.LibraryManagerEventsHelper: Processing 1 episodes with event type Update
[2024-12-16 23:29:24.039 -06:00] [INF] [29] Trakt.Helpers.LibraryManagerEventsHelper: No shows with event type Remove to process
[2024-12-16 23:29:24.042 -06:00] [INF] [29] Trakt.Helpers.LibraryManagerEventsHelper: No shows with event type Add to process
[2024-12-16 23:29:24.043 -06:00] [INF] [29] Trakt.Helpers.LibraryManagerEventsHelper: No shows with event type Update to process
[2024-12-16 23:30:13.452 -06:00] [INF] [61] IntroSkipper.Services.Entrypoint: Initiating automatic analysis task
[2024-12-16 23:30:13.454 -06:00] [INF] [61] IntroSkipper.Manager.QueueManager: Limiting analysis to the following libraries: ["Archived Shows", "Shows"]
[2024-12-16 23:30:13.456 -06:00] [INF] [61] IntroSkipper.Manager.QueueManager: Analysis settings have been changed to: 35% / 20m and a minimum of 15s
[2024-12-16 23:30:13.459 -06:00] [INF] [61] IntroSkipper.Manager.QueueManager: Running enqueue of items in library "Archived Shows"
[2024-12-16 23:30:13.587 -06:00] [INF] [61] IntroSkipper.Manager.QueueManager: Running enqueue of items in library "Shows"
[2024-12-16 23:30:13.593 -06:00] [INF] [61] IntroSkipper.Services.Entrypoint: [Mode: Introduction] Analyzing 11 files from "What We Do in the Shadows" season 6
[2024-12-16 23:30:13.909 -06:00] [WRN] [61] IntroSkipper.Services.Entrypoint: Chromaprint returned 0 points for ""C:\Media\TV\What We Do in the Shadows\Season 6\What We Do in the Shadows - S06E11 - The Finale WEBDL-1080p.mkv""
[2024-12-16 23:30:13.938 -06:00] [INF] [61] IntroSkipper.Services.Entrypoint: [Mode: Credits] Analyzing 11 files from "What We Do in the Shadows" season 6
[2024-12-16 23:30:14.274 -06:00] [INF] [61] IntroSkipper.Services.Entrypoint: [Mode: Recap] Analyzing 11 files from "What We Do in the Shadows" season 6
[2024-12-16 23:30:14.278 -06:00] [INF] [61] IntroSkipper.Services.Entrypoint: [Mode: Preview] Analyzing 11 files from "What We Do in the Shadows" season 6
[2024-12-16 23:30:48.793 -06:00] [INF] [61] Emby.Server.Implementations.IO.LibraryMonitor: "The Finale" ("C:\Media\TV\What We Do in the Shadows\Season 6\What We Do in the Shadows - S06E11 - The Finale WEBDL-1080p.mkv") will be refreshed.
[2024-12-16 23:30:48.796 -06:00] [INF] [61] Emby.Server.Implementations.IO.LibraryMonitor: "What We Do in the Shadows" ("C:\Media\TV\What We Do in the Shadows") will be refreshed.
[2024-12-16 23:30:48.797 -06:00] [INF] [61] Emby.Server.Implementations.IO.LibraryMonitor: "Season 6" ("C:\Media\TV\What We Do in the Shadows\Season 6") will be refreshed.
[2024-12-16 23:30:48.799 -06:00] [INF] [26] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"C:\Media\TV\What We Do in the Shadows\Season 6\What We Do in the Shadows - S06E11 - The Finale WEBDL-1080p.mkv\" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"
[2024-12-16 23:30:58.877 -06:00] [INF] [61] Trakt.Helpers.LibraryManagerEventsHelper: Timer elapsed - processing queued items
[2024-12-16 23:30:58.879 -06:00] [INF] [61] Trakt.Helpers.LibraryManagerEventsHelper: No movies with event type Remove to process
[2024-12-16 23:30:58.882 -06:00] [INF] [61] Trakt.Helpers.LibraryManagerEventsHelper: No movies with event type Add to process
[2024-12-16 23:30:58.883 -06:00] [INF] [61] Trakt.Helpers.LibraryManagerEventsHelper: No movies with event type Update to process
[2024-12-16 23:30:58.885 -06:00] [INF] [61] Trakt.Helpers.LibraryManagerEventsHelper: No episodes with event type Remove to process
[2024-12-16 23:30:58.886 -06:00] [INF] [61] Trakt.Helpers.LibraryManagerEventsHelper: No episodes with event type Add to process
[2024-12-16 23:30:58.887 -06:00] [INF] [61] Trakt.Helpers.LibraryManagerEventsHelper: Processing 1 episodes with event type Update
[2024-12-16 23:30:59.194 -06:00] [INF] [61] Trakt.Helpers.LibraryManagerEventsHelper: No shows with event type Remove to process
[2024-12-16 23:30:59.197 -06:00] [INF] [61] Trakt.Helpers.LibraryManagerEventsHelper: No shows with event type Add to process
[2024-12-16 23:30:59.198 -06:00] [INF] [61] Trakt.Helpers.LibraryManagerEventsHelper: No shows with event type Update to process
[2024-12-16 23:31:48.874 -06:00] [INF] [61] IntroSkipper.Services.Entrypoint: Initiating automatic analysis task
[2024-12-16 23:31:48.877 -06:00] [INF] [61] IntroSkipper.Manager.QueueManager: Limiting analysis to the following libraries: ["Archived Shows", "Shows"]
[2024-12-16 23:31:48.878 -06:00] [INF] [61] IntroSkipper.Manager.QueueManager: Analysis settings have been changed to: 35% / 20m and a minimum of 15s
[2024-12-16 23:31:48.881 -06:00] [INF] [61] IntroSkipper.Manager.QueueManager: Running enqueue of items in library "Archived Shows"
[2024-12-16 23:31:49.001 -06:00] [INF] [61] IntroSkipper.Manager.QueueManager: Running enqueue of items in library "Shows"
```

**Comment by AbandonedCart** [comment]
Sorry you went through all those steps over it. It sounds like the issue is likely that the scan of the file is triggered as the file is being copied in and, subsequently, the analysis is also being triggered too soon. I doubt this is something you could fix on your end any way other than copying the files into the library while the server is offline.
